global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['api-gateway:8000']

  - job_name: 'push-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['push-service:8001']

  - job_name: 'customer-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['customer-service:8002']

  - job_name: 'media-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['media-service:8003']

  - job_name: 'audit-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['audit-service:8004']