"""Auto-generated migration 20240906_230912

Revision ID: 9d48609a83ec
Revises: 34e051d806d5
Create Date: 2024-09-06 23:09:14.526941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d48609a83ec'
down_revision: Union[str, None] = '34e051d806d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_devices', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customer_devices', 'customer_users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer_devices', type_='foreignkey')
    op.drop_column('customer_devices', 'user_id')
    # ### end Alembic commands ###
